### ISSUE TITLE
B1 cannot print when setting density to 6

### ISSUE THREAD

**Issue by xfqz86** [MultiMote/niimblue#15]
B1 cannot print when setting density to 6, because the density of B1 is only supported up to 5 at most.

**Comment by MultiMote** [comment]
Unfortunately, I could not find a place where I can get a list of supported printer densities. So I just added minimum and maximum values to the form. Otherwise i will need to write each printer rule manually.

Supported label types and some other info I got here: https://oss-print.niimbot.com/public_resources/static_resources/devices.json
There may be another source for the density range.

**Comment by xfqz86** [comment]
In you provide URL, `solubilitySetStart` is the minimum density supported by the printer, `solubilitySetEnd` is the maximum, and `solubilitySetDefault` is the default

**Comment by MultiMote** [comment]
What a strange naming 🤦‍♂️
I had not even had a thought that this parameter meant density.

**Comment by MultiMote** [comment]
Done.
